services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    branch: main
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
            name: laravel-db
            property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_db
      - key: DB_USERNAME
        value: laravel
      - key: DB_PASSWORD
        fromService:
            name: laravel-db
            property: password
